udo: required
addons:
  chrome: stable
language: node_js
node_js:
  - "12.6.0"
branches:
  only:
    - ngrx
before_script:
  - npm install -g @angular/cli
script:
  - npm install
  - ng build --prod
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
